import { afterAll, describe, expect, it } from 'vitest'
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as os from 'node:os'
import { removeSync } from '../../core/src/repo/remove'
import { createBook, documentHash, parseDocument, saveAuthorDocument, serializeDocument, paths } from '../../core/src/index'
import { bookRootOfBookIdFor } from '../src/index'
import { createNovelTools } from '../src/novel-tools'
import { StudyService } from '../src/study/service'
import { decideTargetForFile } from '../src/gates'
import { createStudyHandler, type StudyWebRuntime } from '../src/study/web'

const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'webnovel-identity-'))
afterAll(() => removeSync(scratch))
const concept = { 状态: '已确认', 核心创意: '审计虚构样例', 题材与目标读者: '审计', 主角核心欲望: '审计', 主要冲突: '审计', 核心看点: '审计', 差异化方向: '审计', 明确不要什么: '审计' } as const
const workspace = (label: string) => fs.mkdtempSync(path.join(scratch, label))
const put = (root: string, relative: string, content: string) => { const target = path.join(root, relative); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); return content }

describe('host adversarial repro', () => {
  it('F02 rejects creation collisions and every ambiguous ID lookup without changing existing books', async () => {
    const ws = workspace('id-collision-')
    const first = createBook({ workspaceRoot: ws, 书名: 'AB', concept })
    expect(first.ok).toBe(true)
    if (!first.ok) throw new Error(first.reason)
    const second = createBook({ workspaceRoot: ws, 书名: 'B!', concept })
    expect(second).toMatchObject({ ok: false })
    expect(fs.existsSync(path.join(ws, 'B!'))).toBe(false)
    // Simulate a previously copied book, not a new book generated by the fixed writer.
    const copy = path.join(ws, 'B!')
    put(copy, '作品契约/契约.md', fs.readFileSync(path.join(first.bookRoot, '作品契约/契约.md'), 'utf8'))
    const agent = { id: 'audit', session: { header: { cwd: ws } } }
    const tools = createNovelTools({ workspaceRoot: () => ws, bookRootOfBookId: bookRootOfBookIdFor })
    for (const target of ['B!', first.bookId]) {
      const selected = await tools.find(t => t.name === 'novel_select_book')!.execute({ bookId: target }, { agent })
      expect(selected).toMatchObject({ ok: false })
    }
    expect(bookRootOfBookIdFor(first.bookId, agent)).toBeUndefined()
    const result = await tools.find(t => t.name === 'novel_new_outline_draft')!.execute({ bookId: first.bookId, 卷: 1, 章名: '不应落稿', 正文: '不得写入任何书' }, { agent })
    expect(result).toMatchObject({ ok: false })
    expect(fs.existsSync(path.join(first.bookRoot, '草稿区/细纲/卷01-不应落稿.md'))).toBe(false)
    expect(() => new StudyService(ws).read({ space: 'book:' + first.bookId, path: '作品契约/契约.md' })).toThrow(/不唯一/)
  })

  it('F03 rejects reserved book names and refuses shared access to legacy overlapping books', async () => {
    const ws = workspace('reserved-book-')
    expect(createBook({ workspaceRoot: ws, 书名: '书房', concept })).toMatchObject({ ok: false })
    const root = path.join(ws, '书房')
    expect(fs.existsSync(root)).toBe(false)
    put(root, '作品契约/契约.md', serializeDocument({ 书id: 'legacy-shared' }, '旧书'))
    const original = put(root, '定稿/正文.md', serializeDocument({ 版本: 1 }, '不能直接改写的定稿'))
    const service = new StudyService(ws)
    expect(service.read({ space: 'book:legacy-shared', path: '定稿/正文.md' }).readOnly).toContain('补偿')
    expect(() => service.read({ space: 'shared', path: '定稿/正文.md' })).toThrow(/重叠/)
    expect(service.shelf()).toMatchObject({ shared: false, sharedError: expect.stringContaining('重叠') })
    expect(() => saveAuthorDocument(root, { path: '定稿/正文.md', expectedHash: documentHash(original), body: '不得覆盖', shared: true })).toThrow(/重叠/)
    const gate = decideTargetForFile(path.join(root, '定稿/正文.md'), { workspaceRoot: () => ws, bookRootOfId: () => root, bookRootForAbs: () => root })
    expect(gate.kind).toBe('deny')
    expect(fs.readFileSync(path.join(root, '定稿/正文.md'), 'utf8')).toBe(original)
    expect(service.search('正文').entries).toHaveLength(1)
  })

  it.runIf(process.platform === 'win32')('F09 canonical draft identity preserves copy-on-save through authenticated HTTP', async () => {
    const ws = workspace('draft-case-')
    const root = path.join(ws, '作品')
    put(root, '作品契约/契约.md', serializeDocument({ 书id: 'b-audit' }, '测试作品'))
    const relative = path.posix.join(paths.草稿目录(1, '开篇'), '稿1.md')
    const original = put(root, relative, serializeDocument({ 身份: { 卷: 1, 章: 1, 章名: '开篇' }, 版本: 1, 角色: '待审稿', 选定: true }, '原稿正文'))
    const agent = { id: 'audit', session: { header: { cwd: ws } }, followup: () => {} }
    const runtime: StudyWebRuntime = { agents: { get: id => id === 'audit' ? agent : undefined, roots: () => [agent] } }
    const handler = createStudyHandler(runtime)
    const origin = 'http://127.0.0.1'
    const ref = { space: 'book:b-audit', path: relative.replace(/\.md$/, '.MD') }
    const post = async (method: string, input: object) => {
      const response = await handler(new Request(origin + '/api/webnovel/study/' + method, { method: 'POST', headers: { 'x-webnovel-request': '1', 'content-type': 'application/json' }, body: JSON.stringify({ sessionId: 'audit', ...input }) }))
      return { status: response.status, value: await response.json() as any }
    }
    {
      const read = await post('read', { ref })
      expect(read.status).toBe(200)
      const saved = await post('save', { ref, hash: read.value.value.hash, body: '覆盖原稿', operationId: 'audit-draft-case-0001' })
      expect(saved.status).toBe(200)
      expect(read.value.value.ref.path).toBe(relative)
      expect(saved.value.value.document.ref.path).toMatch(/稿2\.md$/)
      expect(fs.existsSync(path.join(root, relative.replace('稿1.md', '稿2.md')))).toBe(true)
      expect(parseDocument(fs.readFileSync(path.join(root, relative), 'utf8')).data?.body).toContain('原稿正文')
      expect(fs.readFileSync(path.join(root, relative), 'utf8')).not.toBe(original)
      fs.writeFileSync(path.join(ws, 'evidence.json'), JSON.stringify({ read, saved, createdDraft2: true }, null, 2))
    }
  })
})
